### ISSUE TITLE
正式版Edge浏览器目前显示有问题

### ISSUE THREAD

**Issue by Chengyunlai** [curly210102/Grow-in-Juejin#23]
我的浏览器信息：
Microsoft Edge
版本 113.0.1774.57 (正式版本) (64 位)

![image](https://github.com/curly210102/Grow-in-Juejin/assets/58059527/a813e950-5556-46ad-8846-873b32407d42)

在其他浏览器上是没有问题的，我测试了例如：谷歌，Dev版本的Edge。

主要问题在活动参与显示：
![image](https://github.com/curly210102/Grow-in-Juejin/assets/58059527/c246f96e-08f7-45e7-830b-5d9243dc59a5)

**Comment by curly210102** [comment]
「进行中的活动」浮标会显示么？
<img width="1440" alt="image" src="https://github.com/curly210102/Grow-in-Juejin/assets/76864176/c7542ed3-0be4-4747-88d1-b45335e111ad">

**Comment by liuyuchuan** [comment]
<img width="398" alt="image" src="https://github.com/curly210102/Grow-in-Juejin/assets/12453224/82e93995-02b5-4437-9610-a0a4f821c315">
这个版本正常显示

**Comment by curly210102** [comment]
@Chengyunlai 请问之后有重现么？或许是跟0.6.3版本修复的bug有关
