### ISSUE TITLE
6月份可以拉取活动7月份的活动不能拉取

### ISSUE THREAD

**Issue by liuyuchuan** [curly210102/Grow-in-Juejin#25]
**请描述一下您遇到的问题**
<img width="714" alt="image" src="https://github.com/curly210102/Grow-in-Juejin/assets/12453224/dd86b8ba-d725-45a8-ae68-97452a697558">
从7.1号开始，持续到7.2号，都未能拉取到活动

**您的浏览器和插件版本是**
1. 浏览器：Google 版本 114.0.5735.133（正式版本） (x86_64)
2. 插件版本：Grow in 掘金 0.6.2

**您的掘金个人主页地址是**
例如：https://juejin.cn/user/641770522163352

**Comment by curly210102** [comment]
感谢反馈，确实有bug，已在 0.6.3 版本改进咯～
