### ISSUE TITLE
金石计划征文活动 10月12日-10月31日

### ISSUE THREAD

**Issue by demo007x** [curly210102/Grow-in-Juejin#26]
活动时间
每个月月初开启挑战，月末最后一天结束，奖金预计15个工作日下发

本期奖金瓜分开启时间：10月12日-10月31日

如何参与
💁🏻 发布文章时选择 [#金石计划征文活动](https://juejin.cn/theme/detail/7218019389664067621?contentType=1) 话题就可以被统计到

**Comment by curly210102** [comment]
OK，已添加活动，本地缓存失效后可以看到效果

**Comment by can4hou6joeng4** [comment]
活动时间
每个月月初开启挑战，月末最后一天结束，奖金预计15个工作日下发

本期奖金瓜分开启时间：11月1日-11月30日

如何参与
💁🏻 发布文章时选择 [#金石计划征文活动](https://juejin.cn/theme/detail/7218019389664067621?contentType=1) 话题就可以被统计到
