### ISSUE TITLE
无法展示进行中的活动

### ISSUE THREAD

**Issue by xujiujiu** [curly210102/Grow-in-Juejin#29]
**请描述一下您遇到的问题**

**您的浏览器和插件版本是**
1. 浏览器：Chrome版本 123.0.6312.107（正式版本） (arm64)
2. 插件版本：0.8.2

**您的掘金个人主页地址是**
[例如：](https://juejin.cn/user/201965869205213)

![image](https://github.com/curly210102/Grow-in-Juejin/assets/25719101/8cf2c383-8bac-45e3-8149-b2a1a4f7a454)

**Comment by curly210102** [comment]
感谢反馈，已更新活动数据。本地数据有缓存明天会更新到，也可以选择重装插件强制刷新
