### ISSUE TITLE
文章数据对不上呀

### ISSUE THREAD

**Issue by miyuesc** [curly210102/Grow-in-Juejin#31]
**请描述一下您遇到的问题**

![image](https://github.com/curly210102/Grow-in-Juejin/assets/50617660/65e2cac6-95fb-4e41-b94f-9b50a50cb765)

**您的浏览器和插件版本是**
1. 浏览器：Chrome 124.0.6367.119 (x64)
2. 插件版本：0.8.2

**您的掘金个人主页地址是**
例如：https://juejin.cn/user/747323639208391

**Comment by curly210102** [comment]
是不是删除了25篇过去的文章？趋势只会在第一次取全部的文章存在本地，之后都是增量更新近期的数据，如果在安装插件之后删除了之前的文章，本地的数据不会被刷新。

如果是这种情况，可以在检测到文章数据不一致的时候，重新全量取一遍

**Comment by miyuesc** [comment]
> 是不是删除了25篇过去的文章？趋势只会在第一次取全部的文章存在本地，之后都是增量更新近期的数据，如果在安装插件之后删除了之前的文章，本地的数据不会被刷新。
> 
> 
> 
> 如果是这种情况，可以在检测到文章数据不一致的时候，重新全量取一遍

不是删除文章的问题，点击掘金header位置那个插入的图标，进插件页面之后，刷新插件页，这个数据也会增加

**Comment by curly210102** [comment]
@miyuesc 刷新插件页不会重新取数据的，目前只有重装插件才会重取。我们先来确认一下，安装插件后有过删除文章的操作吗？

**Comment by miyuesc** [comment]
> @miyuesc 刷新插件页不会重新取数据的，目前只有重装插件才会重取。我们先来确认一下，安装插件后有过删除文章的操作吗？

@curly210102  没有喔，我录了个屏，最后一次刷新的时候已经变成 143 了，只是因为录屏时限没有录进去

[chrome-capture-2024-5-11.webm](https://github.com/curly210102/Grow-in-Juejin/assets/50617660/b7c066d3-54cc-46a6-bdd5-807c32918ef0)

**Comment by curly210102** [comment]
@miyuesc 哦～原来是这样，了解了，我研究一下

**Comment by curly210102** [comment]
@miyuesc 0.8.3 版本修复，已经在 Chrome 插件市场发布了，可以更新看看

**Comment by miyuesc** [comment]
> @miyuesc 0.8.3 版本修复，已经在 Chrome 插件市场发布了，可以更新看看

看起来已经可以了
